fields = (('publisher_contact',
           'Contact',
           'Email or URL for publisher'),
          ('publisher_description',
           'Description',
           "General description of Publisher's role and activities"),
          ('publisher_agencies',
           'Organisations / agencies covered',
           'Whose activities does this publisher publish?'),
          ('publisher_timeliness',
           'Timeliness of Data',
           'How up do date is the data when published?'),
          ('publisher_frequency',
           'Frequency of publication',
           'How often is IATI data refreshed?  Monthly/Quarterly?'),
          ('publisher_units',
           'Units of Aid',
           'A description of any hierarchical reporting units used and how they are applied'),
          ('publisher_segmentation',
           'Segmentation of Published Data',
           'Is IATI data published by country, regions?'),
          ('publisher_refs',
           'Data Definitions and References',
           "Links to guides, explanations, codelists on the publisher's own site that clarify their data"),
          ('publisher_field_exclusions',
           'Field Exclusions',
           'What fields does the publisher never use - and for what reason'),
          ('publisher_record_exclusions',
           'Record Exclusions',
           "What are the policies for excluding particular activities, or parts of an activity's data?"),     
          ('publisher_thresholds',
           'Thresholds',
           'What are the thresholds below which data or whole activities are not published?'),
          ('publisher_constraints',
           'Other Constraints',
           'Other policies that restrict full compliance with the standard'),
          ('publisher_data_quality',
           'Data Quality',
           "Publisher's comment on the status and accuracyof the data - audited/verified, operational/sub to change, etc"),
          ('publisher_ui',
           'User Interface',
           "Link to publisher's own public user activity interface"),
          )
publisher_record_fields = fields
